spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiba
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  servlet:
    multipart:
      max-file-size: 50MB